apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mname
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # base64 encoded 'admin'
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 encoded 'password'
  MONGO_DATABASE: Zmxhc2tfZGI= # base64 encoded 'flask_db'
  MONGO_USERNAME: YXNo # base64 encoded 'ash'
  MONGO_PASSWORD: YXNoOTkwMA== # base64 encoded 'ash9900'
